# Generated by Django 4.2.26 on 2026-01-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0297_outgoingmail"),
        ("pretix_bounces", "0003_mailalias_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailalias",
            name="outgoing_mail",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pretixbase.outgoingmail",
            ),
        ),
        migrations.AlterField(
            model_name="mailalias",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
